### ISSUE TITLE
Unrecognized characters in  江西_四川_重庆_西藏 Dataset

### ISSUE THREAD

**Issue by GohUnTsuan** [sammo3182/regioncode#15]
In ./data/江西_四川_重庆_西藏.xlsx, some name/sname values contain unrecognized or incorrect characters. For example, in line 46,  '1988_name' has value ' 内江市' instead of '内江市‘. Function will return NA because of unrecognized characters.

**Comment by chenyuanqian18** [comment]
[江西_四川_重庆_西藏.xlsx](https://github.com/sammo3182/regioncode/files/5944120/_._._.xlsx)

**Comment by chenyuanqian18** [comment]
[江西_四川_重庆_西藏.xlsx](https://github.com/sammo3182/regioncode/files/5957519/_._._.xlsx)
