### ISSUE TITLE
Toy data failed to load

### ISSUE THREAD

**Issue by GohUnTsuan** [sammo3182/regioncode#21]
I try to run the example code in help file,

```
library(regioncode)

regioncode(data_input = corruption$prefecture_id,
           year_from = 2019,
          year_to = 1999)
```
But it seem to doesn't  work. The error message is 
> Error in regioncode(data_input = corruption$prefecture_id, year_from = 2019,  : 
> object 'corruption' not found

I guess the toy data `corruption` may not be successfully loaded.

**Comment by sammo3182** [comment]
Let's put the issues about the same topic together
