### ISSUE TITLE
(Maybe) A mistake in raw data

### ISSUE THREAD

**Issue by yangtzesyy** [sammo3182/regioncode#26]
There might be a mistake in the region_table. (don't know what "<U+00A0>" stands for)

region_table[408,"2019_name"]
[1] "<U+00A0>成都市"

**Comment by yangtzesyy** [comment]
> region_table[408,c("2017_name","2018_name","2019_name")]
         2017_name      2018_name      2019_name
408 <U+00A0>成都市 <U+00A0>成都市 <U+00A0>成都市

**Comment by yangtzesyy** [comment]
mistakes fixed

**Comment by sammo3182** [comment]
Check the dataset to rule out similar error across the dataset
