### ISSUE TITLE
Vignette

### ISSUE THREAD

**Issue by sammo3182** [sammo3182/regioncode#9]
See the reference from `countrycode`, `dotwhisker`, and `interplot`

Adding a Chinese version

**Comment by Calvin-sen** [comment]
I'm so sorry, but I failed to find the vignette of `countrycode`. Here are the codes:
```
install.packages("countrycode")
vignette(package = "countrycode")
```
and it showed `no vignettes found`.

**Comment by sammo3182** [comment]
> I'm so sorry, but I failed to find the vignette of `countrycode`. Here are the codes:
> 
> ```
> install.packages("countrycode")
> vignette(package = "countrycode")
> ```
> 
> and it showed `no vignettes found`.

See the readme file or the package website.
